/*
EX. 1
UMA LISTA COM O NOME DE TODAS AS GAFANHOTAS
*/
SELECT * FROM GAFANHOTOS
WHERE SEXO = 'F';

/*
EX. 2
UMA LISTA COM OS DADOS DE TODOS AQUELES QUE NASCERAM ENTRE 01/01/2000 E 31/12/2015
*/
SELECT * FROM GAFANHOTOS
WHERE NASCIMENTO BETWEEN '01/01/00' AND '31/12/15';

/*
EX. 3
UMA LISTA COM O NOME DE TODOS OS HOMENS QUE TRABALHAM COMO PROGRAMADORES
*/
SELECT * FROM GAFANHOTOS
WHERE SEXO = 'M' AND PROFISSAO = 'PROGRAMADOR';

/*
EX. 4
UMA LISTA COM OS DADOS DE TODAS AS MULHERES QUE NASCERAM NO BRASIL E QUE TÊM SEU NOME INICIANDO COM A LETRA “J”
*/
SELECT * FROM GAFANHOTOS
WHERE SEXO = 'F' AND NACIONALIDADE = 'BRASIL' AND NOME LIKE 'J%';

/*
EX. 5
UMA LISTA COM O NOME E NACIONALIDADE DE TODOS OS HOMENS QUE TÊM SILVA NO NOME, NÃO NASCERAM NO BRASIL E PESAM MENOS DE 100 KG
*/
SELECT * FROM GAFANHOTOS
WHERE SEXO = 'M' AND NOME LIKE '%SILVA%' AND NACIONALIDADE NOT LIKE 'BRASIL' AND PESO < 100;

/*
EX. 6
QUAL A MAIOR ALTURA ENTRE GAFANHOTOS HOMENS QUE MORAM NO BRASIL
*/
SELECT MAX(ALTURA) FROM GAFANHOTOS 
WHERE SEXO = 'M' AND NACIONALIDADE = 'BRASIL';

/*
EX. 7
QUAL É A MÉDIA DE PESO DOS GAFANHOTOS CADASTRADOS
*/
SELECT AVG(PESO) FROM GAFANHOTOS;

/*
EX. 8
QUAL É O MENOR PESO ENTRE OS GAFANHOTOS MULHERES QUE NASCERAM FORA DO BRASIL E ENTRE 01/01/1990 E 31/12/2000?
*/
SELECT MIN(PESO) FROM GAFANHOTOS 
WHERE SEXO = 'F' AND NACIONALIDADE NOT LIKE 'BRASIL' 
AND NASCIMENTO BETWEEN '01/01/90' AND '31/12/00'; 

/*
EX. 9
QUANTAS GAFANHOTAS MULHERES TEM MAIS DE 1,90M DE ALTURA?
*/
SELECT COUNT(*) FROM GAFANHOTOS WHERE SEXO = 'F' AND ALTURA > '1.90';

/*
EX. 10
UMA LISTA COM AS PROFISSÕES DOS GAFANHOTOS E SEUS RESPECTIVOS QUANTITATIVOS;
*/
SELECT PROFISSAO, COUNT(*) FROM GAFANHOTOS
GROUP BY PROFISSAO;

/*
EX. 11
QUANTOS GAFAHOTOS HOMENS E QUANTAS MULHERES NASCERAM APÓS 01/01/2005?
*/
SELECT SEXO, COUNT(*) FROM GAFANHOTOS
WHERE NASCIMENTO > '01/01/05'
GROUP BY SEXO;

/*
EX. 12
UMA LISTA COM OS GAFANHOTOS QUE NASCERAM FORA DO BRASIL, MOSTRANDO O PAÍS DE ORIGEM E O TOTAL DE PESSOAS NASCIDAS LÁ. SÓ NOS INTERESSAM OS PAÍSES QUE TIVEREM MAIS DE 3 GAFANHOTOS COM ESSA NACIONALIDADE
*/
SELECT NACIONALIDADE, COUNT(*) FROM GAFANHOTOS
WHERE SEXO = 'M' AND NACIONALIDADE <> 'BRASIL'
GROUP BY NACIONALIDADE
HAVING COUNT(*)>3;

/*
EX. 13
UMA LISTA AGRUPADA PELA ALTURA DOS GAFANHOTOS, MOSTRANDO QUANTAS PESSOAS PESAM MAIS DE 100kg E QUE ESTÃO ACIMA DA MÉDIA DE ALTURA DE TODOS OS CADASTRADOS;
*/
SELECT ALTURA, COUNT(*) FROM GAFANHOTOS
WHERE SEXO = 'M' AND PESO > '100'
GROUP BY ALTURA
HAVING ALTURA > (SELECT AVG(ALTURA) FROM GAFANHOTOS) ;
