SELECT * FROM CURSOS
WHERE NOME LIKE 'P%';

SELECT * FROM CURSOS
WHERE NOME LIKE '%A';

SELECT * FROM CURSOS
WHERE NOME LIKE '%A%';

SELECT * FROM CURSOS
WHERE NOME NOT LIKE '%A%';

SELECT * FROM CURSOS
WHERE NOME LIKE 'PH%P';

SELECT * FROM CURSOS
WHERE NOME LIKE 'PH%P%';

SELECT * FROM CURSOS
WHERE NOME LIKE 'PH%P_';

SELECT * FROM CURSOS
WHERE NOME LIKE 'P__T%';

SELECT DISTINCT NACIONALIDADE FROM GAFANHOTOS
ORDER BY NACIONALIDADE;

SELECT COUNT(*) FROM CURSOS;

SELECT * FROM CURSOS WHERE CARGA > 40;

SELECT COUNT(*) FROM CURSOS WHERE CARGA > 40;

SELECT MAX(CARGA) FROM CURSOS;

SELECT MAX(TOTAULAS) FROM CURSOS WHERE ANO = '2016';

SELECT MIN(TOTAULAS) FROM CURSOS;

SELECT NOME, MIN(TOTAULAS) FROM CURSOS WHERE ANO = '2016';

SELECT SUM(TOTAULAS) FROM CURSOS WHERE ANO = '2016';

SELECT AVG(TOTAULAS) FROM CURSOS WHERE ANO = '2016';
