SELECT * FROM CURSOS
ORDER BY nome DESC;

SELECT NOME, DESCRICAO, CARGA, ANO FROM CURSOS
WHERE ANO <= '2016'
ORDER BY NOME, ANO;

SELECT NOME, DESCRICAO, CARGA, ANO FROM CURSOS
WHERE ANO <> '2016'
ORDER BY NOME, ANO;

SELECT NOME, ANO FROM CURSOS
WHERE ANO BETWEEN 2014 AND 2016
ORDER BY ANO, NOME;

SELECT NOME, ANO FROM CURSOS
WHERE ANO BETWEEN 2014 AND 2016
ORDER BY ANO DESC, NOME;

SELECT NOME, DESCRICAO, ANO FROM CURSOS
WHERE ANO IN (2014, 2016, 2020)
ORDER BY ANO;

SELECT NOME, CARGA, TOTAULAS FROM CURSOS
WHERE CARGA > 35 AND TOTAULAS < 30;

SELECT NOME, CARGA, TOTAULAS FROM CURSOS
WHERE CARGA > 35 OR TOTAULAS < 30;