SELECT ANO, COUNT(*) FROM CURSOS
WHERE TOTAULAS > 30
GROUP BY ANO
HAVING ANO > 2013
ORDER BY COUNT(*) DESC;

SELECT AVG(CARGA), COUNT(*) FROM CURSOS
WHERE ANO > 2015
GROUP BY CARGA
HAVING CARGA > (SELECT AVG(CARGA) FROM CURSOS);

