USE CADASTRO;
DESCRIBE GAFANHOTOS;
ALTER TABLE GAFANHOTOS
ADD COLUMN CURSOPREFERIDO INT;

ALTER TABLE GAFANHOTOS
ADD FOREIGN KEY (CURSOPREFERIDO)
REFERENCES CURSOS(IDCURSO);

SELECT * FROM GAFANHOTOS;
SELECT * FROM CURSOS;

UPDATE GAFANHOTOS SET CURSOPREFERIDO = '6' WHERE ID = '1';

DELETE FROM CURSOS WHERE IDCURSO = '9';

SELECT G.NOME, C.NOME, C.ANO
FROM GAFANHOTOS AS G INNER JOIN CURSOS AS C
ON C.IDCURSO = G.CURSOPREFERIDO
ORDER BY G.NOME;